postgres:
  database: chat_with_anyone
  user: chat_with_anyone
  password: chat_with_anyone
  host: localhost
  port: 5432
  pool_min_size: 1
  pool_max_size: 5

host: 127.0.0.1
port: 8080
token_expires:
  hours: 2
